version: "2"
services:
  db:
    image: postgres
    container_name: python_db
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=pythondb
  web:
    build: .
    image: python_ui
    container_name: python_ui
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgres://postgres@db/pythondb
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db